#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0  -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           8

bspc config click_to_focus             true
bspc config focus_by_distance          true
bspc config focus_follows_pointer true
bsoc config history_aware_focus        true


bspc config single_monocle             false
bspc config borderless_monocole        true
bspc config gapless_monocole           true

bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true


bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

bspc config normal_border_color     "#000000"
bspc config active_border_color     "#ffffff"
bspc config focused_border_color    "#4747ff"
bspc config presel_feedback_color   "#f0f0f0"
bspc config urgent_border_color     "#ff4747"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
